%function Hd =FIR 1
%FIR 1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 19-Nov-2018 22:00:01

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in kHz.
Fs = 48;  % Sampling Frequency khz

N    = 49;       % Order
Fc   = 3;        % Cutoff Frequency khz
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
hn  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(hn);
digit=12;
Amp=pow(2,digit);
d=int16(hn*Amp);
hqn=double(d)/Amp;
subplot(2,1,1)
freqz(hn)
title('Frequency response of the original filter')
subplot(2,1,2)
freqz(hqn)
title('Frequency response of the quantized filter')
